### ISSUE TITLE
What is meant by "without a battery" in top level README.md ?

### ISSUE THREAD

**Issue by jstickley** [facebook/FAI-PEP#230]
In top level README one of the bullets about performance metrics says,

"energy/power : the energy per inference and average power of running the the ML model on a phone without battery"

I assume the "the the" is a typing error that should be "the".

But what about "without battery" ? If inference engine hardware in mobile phones could truly run without a battery that would be very low power indeed !! Is this a typo or if not, what is meant by this ?

-- jS

**Comment by sf-wind** [comment]
Thanks, please check: https://github.com/facebook/FAI-PEP/wiki/Work-on-Power-Energy

It explains the procedure to measure the power/energy. 

Thanks for the typo check :)

**Comment by hl475** [comment]
Will close the issue as it has been addressed in https://github.com/facebook/FAI-PEP/pull/295.
