### ISSUE TITLE
Problems when running the experiment with docker

### ISSUE THREAD

**Issue by DeeperMind** [facebook/FAI-PEP#284]
When trying to run the experiment with docker for TFLite example, I encountered the following error:

```
+ python /tmp/FAI-PEP/benchmarking/run_bench.py -b /tmp/FAI-PEP/specifications/models/tflite/mobilenet_v2/mobilenet_v2_0.35_96.json --config_dir /tmp/config
usage: run_bench.py [-h] [--app_id APP_ID] [-b BENCHMARK_FILE] [--lab]
                    [--logger_level {info,warning,error}] [--remote]
                    --root_model_dir ROOT_MODEL_DIR [--token TOKEN]
                    [-c CUSTOM_BINARY] [--pre_built_binary PRE_BUILT_BINARY]
                    [--user_string USER_STRING]
run_bench.py: error: argument --root_model_dir is require
```

Does anyone know how to resolve this? Did I missed anything before running the example?

**Comment by hl475** [comment]
I checked [docker_tflite.sh](https://github.com/facebook/FAI-PEP/blob/master/specifications/docker/docker_tflite.sh), and I think `root_model_dir` is missing [here](https://github.com/facebook/FAI-PEP/blob/master/specifications/docker/docker_tflite.sh#L45-L56). A quick solution is to add `root_model_dir` like this [one](https://github.com/facebook/FAI-PEP/blob/master/.circleci/tests/test_tflite.sh#L26) into docker_tflite.sh file. Can you try that out to see if that could solve the problem? If so, it will be much appreciated if you can create a PR to fix this as well as the one in [docker_pytorch.sh](https://github.com/facebook/FAI-PEP/blob/master/specifications/docker/docker_pytorch.sh#L42-L54).

**Comment by sf-wind** [comment]
Right, please file a PR :) Thanks.

**Comment by DeeperMind** [comment]
PR created. Thank you for your help!

**Comment by hl475** [comment]
PR landed. Thanks again!
