### ISSUE TITLE
Checking if the key exists in dictionary instead of using dict.get(key, None)

### ISSUE THREAD

**Issue by farziengineer** [facebook/FAI-PEP#298]
https://github.com/facebook/FAI-PEP/blob/a26fa88ae02e8db7ff51924735f57d95e57d26d5/benchmarking/driver/benchmark_driver.py#L35-L36

https://github.com/facebook/FAI-PEP/blob/a26fa88ae02e8db7ff51924735f57d95e57d26d5/benchmarking/driver/benchmark_driver.py#L42-L43
Some places in this file `FAI-PEP/benchmarking/driver/benchmark_driver.py` has check if a key is in the dictionary and then tries to access it. It may be inefficient and less clean to go through
the dictionary twice. Can I raise a PR to change these to

```python
minfo["shared_libs"] = info.get("shared_libs", "") 
cinfo["shared_libs"] = info.get("shared_libs", "")
```

**Comment by sf-wind** [comment]
Please do, thanks
